name: Youtube Downloader

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "Paste Youtube Video URL:"
        required: true
        type: string
      media_type:
        description: "Select Output:"
        required: true
        type: choice
        default: "Video with Audio"
        options:
          - "Video with Audio"
          - "Audio Only"

jobs:
  Download-Video:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: AnimMouse/setup-yt-dlp@v3

      - uses: AnimMouse/setup-yt-dlp/cookies@v3
        with:
          cookies: ${{ secrets.YOUTUBE_COOKIES }}

      - name: Get video title
        id: get_title
        run: |
          title=$(yt-dlp --get-title "${{ github.event.inputs.youtube_url }}" | sed 's/[^a-zA-Z0-9_.-]/_/g')
          echo "title=$title" >> "$GITHUB_OUTPUT"

      - name: Download media file
        run: |
          media_path="${{ steps.get_title.outputs.title }}"
          if [ "${{ github.event.inputs.media_type }}" == "Video with Audio" ]; then
            yt-dlp -o "${media_path}.%(ext)s" -f 'bestvideo+bestaudio/best' --recode-video mp4 "${{ github.event.inputs.youtube_url }}"
          else
            yt-dlp -o "${media_path}.%(ext)s" -x --audio-format mp3 "${{ github.event.inputs.youtube_url }}"
          fi
          echo "DOWNLOADED_FILE_PATH=$(ls ${media_path}.*)" >> $GITHUB_ENV

      - uses: AnimMouse/setup-yt-dlp/cookies/update@v3
        with:
          cookies_secret_name: YOUTUBE_COOKIES
          token: ${{ secrets.FRONTSTAGE_YOUTUBE_REFRESH }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_title.outputs.title }}
          path: ${{ env.DOWNLOADED_FILE_PATH }}
