name: Youtube Downloader

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "Paste Youtube Video URL:"
        required: true
        type: string
      media_type:
        description: "Select Output:"
        required: true
        type: choice
        default: "video"
        options:
          - "video"
          - "audio"

jobs:
  download-media:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
          pip install yt-dlp

      - name: Download video
        if: github.event.inputs.media_type == 'video'
        run: |
          yt-dlp -f 'bestvideo+bestaudio/best' "${{ github.event.inputs.youtube_url }}"

      - name: Download audio
        if: github.event.inputs.media_type == 'audio'
        run: |
          yt-dlp -x --audio-format mp3 "${{ github.event.inputs.youtube_url }}"

      - name: Upload downloaded file as an artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./*
