name: Youtube Downloader

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "Paste Youtube Video URL:"
        required: true
        type: string
      media_type:
        description: "Select Output:"
        required: true
        type: choice
        default: "Video with Audio"
        options:
          - "Video with Audio"
          - "Audio Only"

jobs:
  download-media:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: AnimMouse/setup-yt-dlp@v3

      - uses: AnimMouse/setup-yt-dlp/cookies@v3
        with:
          cookies: ${{ secrets.YOUTUBE_COOKIES }}

      - name: Download video
        if: github.event.inputs.media_type == 'Video with Audio'
        run:
          yt-dlp -f 'bestvideo+bestaudio/best' "${{
          github.event.inputs.youtube_url }}"

      - name: Download audio
        if: github.event.inputs.media_type == 'Audio Only'
        run:
          yt-dlp -x --audio-format mp3 "${{ github.event.inputs.youtube_url }}"

      - uses: AnimMouse/setup-yt-dlp/cookies/update@v3
        with:
          cookies_secret_name: YOUTUBE_COOKIES
          token: ${{ secrets.FRONTSTAGE_YOUTUBE_REFRESH }}

      - uses: actions/upload-artifact@v4
        with:
          path: ./*
